[package]
name = "valid_go_move_regex"
version = "2.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive"] }
clap-stdin = "0.6.0"
goban = "0.18.1"
sgf-parse = "4.2.2"
